[package]
name = "rusdig"
description = "DNS, the Rust way."
license = "MIT"
repository = "https://github.com/Kek5chen/rusdig"
version = "0.2.0"
edition = "2021"


[dependencies]
bitflags = "2.6.0"
static_assertions = "1.1.0"
thiserror = "1.0.64"
bytemuck = "1.19.0"
rand = "0.9.0-alpha.2"